### ISSUE TITLE
Is to import ManyToManyField possible ?

### ISSUE THREAD

**Issue by microniko** [edcrewe/django-csvimport#40] opened 2014-09-03 20:35 UTC
All in the title.

**Comment by edcrewe** [comment] 2017-05-30 17:02
Hi,

Sorry csvimport currently only looks for ForeignKey relationships currently.
It doesnt do so in a particularly sophisticated manner, since this is CSV data.

If it finds something marked as an ForeignKey with a lookup field in its model mappings, then it checks if the data exists already for the related model and pulls back an id for the field or creates a new entry if possible in the fkey model and pulls back a new id. Based on an assumed unique lookup field.

This may be sufficient for ManyToMany fields if they are not using an intermediate model.
However the code doesn't look for these type of fields so I think it may just treat them as normal data fields.
You can try making an Fkey mapping for them and see if it works, eg. for an organisation column, org, that holds the unique name of the organisation you add
column2=org(Organisation|name)
... for it to replace with org_id FKey

The problem is that for ManyToMany then you would be getting data populated in both directions.
In general there is also a limit to how csvimport could handle this unless their was more metadata mapping options and processing of what you were storing in your csvfile in a field to look up its foreign key unique instance.

Given the possible custom behaviour required, the best option is probably just create a temporary model with the lookup data in as columns, you can use 
inspectcsv importfile.csv > models.py
to automatically generate the temporary model from your CSV file
... then use a bulk insert database query to take the data in it and populate complex relations of the final model tables appropriately.

Ed

**Closed** 2017-05-30 17:08 UTC
